config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get "/profile", to: "profile#show"

  authenticated :user do
    root "main#welcome", as: :authenticated_root
  end

  # landing page if you are not logged in
  root "main#welcome" 

  resources :days 
  resources :exercises
  resources :challenges
  resources :children
 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
# == Schema Information
#
# Table name: challenges
#
#  id             :integer          not null, primary key
#  active         :boolean
#  number_of_days :integer
#  title          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  child_id       :integer
#  user_id        :integer
#
class Challenge < ApplicationRecord
  
  has_many  :days, class_name: "Day", foreign_key: "challenge_id"
  # belongs_to :user
  # belongs_to :child

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: %i[ show edit update destroy ]

  # GET /challenges or /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1 or /challenges/1.json
  def show
    @challenge_id = params.fetch(:id).to_i

  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges or /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to challenge_url(@challenge), notice: "Challenge was successfully created." }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1 or /challenges/1.json
  def update
    @challenge = Challenge.new(challenge_params)
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to challenge_url(@challenge), notice: "Challenge was successfully updated." }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1 or /challenges/1.json
  def destroy
    @challenge.destroy

    respond_to do |format|
      format.html { redirect_to challenges_url, notice: "Challenge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def challenge_params
      params.require(:challenge).permit( :active, :title, :number_of_days)
    end
end

app/views/challenges/_challenge.html.erb
<div class="d-grid gap-2 col-6 mx-auto" id="<%= dom_id challenge %>">
  <button class="btn m-2 p-3 fs-4" >
    <%= link_to "#{challenge.number_of_days} #{challenge.title}", challenge, class: "link" %></button>
</div>

app/views/challenges/_form.html.erb
<%= form_with(model: challenge) do |form| %>
  <% if challenge.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
        <% challenge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# <div>
    <%= form.label :user_id, style: "display: block" 
    <%= form.hidden_field :user_id %>
  <%# </div> %> 

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <%# <div>
    <%= form.label :child_id, style: "display: block"
    <%= form.hidden_field :child_id %>
  <%# </div>  %>

 <div>
    <%= form.label :number_of_days, style: "display: block" %>
    <%= form.text_field :number_of_days %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<% if current_user.email == "alina@example.com" %>

<h1>Editing challenge</h1>
<%= render "form", challenge: @challenge %>
<br>
<div>
  <%= link_to "Show this challenge", @challenge %> |
  <%= link_to "Back to challenges", challenges_path %>
</div>

<%else%>
<p>Sorry!! You should be admin</p>
<%end%>

app/views/challenges/index.html.erb
<h1 id="header">Challenges</h1>
<div id="challenges">
  <% @challenges.order(:number_of_days => :asc).each do |challenge| %>
    <%= render challenge %>
  <% end %>
</div>

<% if current_user.email == "alina@example.com" %>
<%= link_to "New challenge", new_challenge_path %>
<%end%>

app/views/challenges/new.html.erb
<% if current_user.email == "alina@example.com" %>
<h1>New challenge</h1>

<%= render "form", challenge: @challenge %>

<br>

<div>
  <%= link_to "Back to challenges", challenges_path %>
</div>
<%else%>
<p>You should be admin</p>
<%end%>

app/views/challenges/show.html.erb
<body class="daysInChallenge">

  <%# <% Child.where(:user_id => current_user.id).each do |c| %>
  <%# <%= link_to  "Back to challenges", "/children/#{c.id}", class: "backLink" %>      
  <%# <% end %> 
  <%= link_to 'Back', '#', class: "backLink", onclick: "event.preventDefault(); history.back();" %>

<div>
<h2 class="headerInDays"><%= @challenge.number_of_days %> Days Challenge</h2>
</div>



<div class="containers">
  <% arr = (1..Day.count + 1).to_a.sort{ rand() - 0.5}[1..@challenge.number_of_days].sort %>
  <% day = 0 %>
   <% arr.each do |num| %>
   <% day= day + 1 %>
  <div class="image-background">

    <a href="<%= day_path(Day.all.sample.id)%>" class="button button--piyo">
        <div class="button__wrapper">
            <span class="button__text"><%= day %> Day</span>
        </div>
        <div class="characterBox">
            <div class="character wakeup">
                <div class="character__face"></div>
            </div>
            <div class="character wakeup">
                <div class="character__face"></div>
            </div>
            <div class="character">
                <div class="character__face"></div>
            </div>
        </div>
    </a>
  </div>
<% end %>
</div>


</div>
<% if current_user.email == "alina@example.com" %>
<div>
  <%= link_to "Edit this challenge", edit_challenge_path(@challenge) %> 
   <%= link_to "Back to challenges", challenges_path %>
  <%= button_to "Destroy this challenge", @challenge, method: :delete %> 
 </div>
 <%end%>

</body>