config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get "/profile", to: "profile#show"

  authenticated :user do
    root "main#welcome", as: :authenticated_root
  end

  # landing page if you are not logged in
  root "main#welcome" 

  resources :days 
  resources :exercises
  resources :challenges
  resources :children
 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  # before_action :set_day
  before_action :set_exercise, only: %i[ show edit update destroy ]

  # GET /exercises or /exercises.json
  def index
    @exercises = Exercise.all
   
  end

  # GET /exercises/1 or /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
    
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises or /exercises.json
  def create
    @exercise = Exercises.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully created." }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1 or /exercises/1.json
  def update
   
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1 or /exercises/1.json
  def destroy
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url, notice: "Exercise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # def set_day
  #   @day = Day.find(params[:id])
  # end

  # Use callbacks to share common setup or constraints between actions.
  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def exercise_params
    params.require(:exercise).permit(:id, :title, :video, :day_id)
  end
end

app/views/exercises/_exercise.html.erb
<div id="<%= dom_id exercise %>">
  <p>
    <strong>Title:</strong>
    <%= exercise.title %>
  </p>
<div class="video-container">
  <%= video_tag("#{exercise.video}", controls: true, class: "video-style", id: "video#{exercise.id + 1}") %>
</div>
</div>

app/views/exercises/_form.html.erb
<%= form_for exercise, url: exercises_path, html: { enctype: "multipart/form-data" } do |f| %>
  <% if exercise.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day_id %><br>
    <%= f.number_field :day_id %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.file_field :video %>
  </div>
  <div class="actions">
    <%= f.submit "Upload Exercise" %>
  </div>
<% end %>

app/views/exercises/_update.html.erb
<%= form_for exercise, url: exercise_path, method: :put, html: { enctype: "multipart/form-data" } do |f| %>


  <% if exercise.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.file_field :video %>
  </div>
  <div class="actions">
    <%= f.submit "Upload Exercise" %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<% if current_user.email == "alina@example.com" %>
<h1>Editing exercise</h1>

<%= render "update", exercise: @exercise %>

<br>

<div>
  <%= link_to "Show this exercise", @exercise %> |
  <%= link_to "Back to exercises", exercises_path %>
</div>
<%end%>

app/views/exercises/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 id="header">Exercises</h1>
<% if current_user.email == "alina@example.com" %>
<p>
<%= link_to "New exercise", new_exercise_path %>
</p>
<% end %>
<div id="exercises">
  <% @exercises.each do |exercise| %> 
     <p><%= exercise.title %></p>
     <div class="video-container">
      <%= video_tag("#{exercise.video}", controls: true, class: "video-style") %>
      </div>
       <p>
       <%= link_to "Show this exercise", exercise %>
      </p>
  <% end %>
   
</div>

app/views/exercises/new.html.erb
<% if current_user.email == "alina@example.com" %>
<h1>New exercise</h1>

<%= render "form", exercise: @exercise %>

<br>

<div>
  <%= link_to "Back to exercises", exercises_path %>
</div>
<%end%>

app/views/exercises/show.html.erb
<p style="color: green"><%= notice %></p>


<%= render @exercise %>

<% if current_user.email == "alina@example.com" %>
<div>
  <%= link_to "Edit this exercise", edit_exercise_path(@exercise) %>
  <%= link_to "Back to exercises", exercises_path %> 

  <%= button_to "Destroy this exercise", @exercise, method: :delete %>  
</div>
<% end %>